### ISSUE TITLE
Small cleanup in oceanv3 netlist

### ISSUE THREAD

**Issue by trentmc** [tokenspice/tokenspice#113]
**TODOs**
- [x] modifiedAgents shouldn't be in oceanv3 netlist directory, they should simply be in /agents/. https://github.com/tokenspice/tokenspice/pull/114/commits/9256eb081c11002a220b05474e4a78a2ca80cf39
- [x] netlists/oceanv3/*.py imports for agents above need updating
- [x] for v3PublisherAgent.py: reconcile with PublisherAgent.py. How: Merge. For testing: it naturally uses test_PublisherAgent.py
- [x] for v3SpeculatorAgent.py: reconcile with SpeculatorAgent.py. How: Merge
- [x] for V3StakerspeculatorAgent.py: reconcile with StakerspeculatorAgent.py. How: merge
- [x] for v3DataconsumerAgent.py: reconcile with DataconsumerAgent.py. How: merge
- [x] for MaliciousPublisherAgent.py: reconcile with PublisherAgent.py. How: don't merge; write test_MaliciousPublisher
- [x] create netlists/oceanv3/tests, and write tests. Can probably keep it simple since we already have sol057/contracts/oceanv3/tests
