### ISSUE TITLE
Clean up oceanv4 branches & PRs

### ISSUE THREAD

**Issue by trentmc** [tokenspice/tokenspice#154]
**Status Quo**

TokenSPICE `main` branch already has Ocean v4 oceanprotocol/contracts + more in it, which (Trent) put there in about Nov 2021. Since then, the oceanprotocol/contract contracts were updated steadily until about mid Feb 2022.
- Up-to-date oceanprotocol/contracts branch:  [`v4main_postaudit`](https://github.com/oceanprotocol/contracts/tree/v4main_postaudit). 
- On Mar 2, 2022, I copied up-to-date v4 contracts into [df-py](https://github.com/oceanprotocol/df-py). I was able to get them compiling with just a few small tweaks.

TokenSPICE has these v4-related issue, branches, and PRs. NOTE: I'm updating this table as I work on it. 

Status | Issue | Branch | PR 
---- | ---- | ---- | ----
HANDLED | #111| [`test_oceanv4`](https://github.com/tokenspice/tokenspice/tree/test_oceanv4), last updated 60 days ago | [`Test oceanv4`](https://github.com/tokenspice/tokenspice/pull/122), opened Dec 6, 2021
HANDLED | #29 | [`oceanv4_netlist`](https://github.com/tokenspice/tokenspice/tree/oceanv4_netlist), last updated 24 days ago | [`Oceanv4 netlist #29`](https://github.com/tokenspice/tokenspice/pull/125), opened Jan 2, 2022
DONE | (part of this issue) | [`issue29-redux`](https://github.com/tokenspice/tokenspice/tree/issue29-redux) | [`issue29-redux`](https://github.com/tokenspice/tokenspice/pull/155)
DONE | [oceanprotocol/contracts #491](https://github.com/oceanprotocol/contracts/issues/491) | [`v4_vesting`](https://github.com/tokenspice/tokenspice/tree/v4_vesting) | (none)

**Target outcome of this issue**

- All the ocean v4 branches are closed
- All the ocean v4 PRs are closed - merged into `main` where it makes sense, or dropped
- TokenSPICE `main` has up-to-date contracts from ocean v4

This is high priority for me (Trent) because I want to use tokenspice infrastructure with up-to-date oceanv4 towards Ocean Data Farming.

**TODOs**

- [x] Re [#111](#111): finish it. Merge PR, delete branch, close issue 
- [x] Re [#29](#29): finish it. Merge PR, delete branch, close issue. And, copy in latest v4 contracts. https://github.com/tokenspice/tokenspice/commit/fd08ba49d06b39244a865e4ede803466042d0130
  - [x] I discovered that I can't readily merge that PR. Better: create new branch [`issue29-redux`](https://github.com/tokenspice/tokenspice/tree/issue29-redux) & PR [`issue29-redux`](https://github.com/tokenspice/tokenspice/pull/155), copy from old branch as needed, merge new branch.
  - [x] Copy in latest oceanv4 contracts, into the (new) PR. Copy from [df-py](https://github.com/oceanprotocol/df-py) which are up-to-date and have latest tweaks (as of Mar 2, 2022).  Commit: https://github.com/tokenspice/tokenspice/pull/155/commits/3ab619074512cf437ad5aaa92ed512a403c7733a
  - [x] Get all unit tests passing in branch [`issue29-redux`](https://github.com/tokenspice/tokenspice/tree/issue29-redux) // PR [`issue29-redux`](https://github.com/tokenspice/tokenspice/pull/155)

Other oceanv4 work, out of scope for here:
- Created a new issue to handle some remaining DRY violations. #156 
- Re [contracts #491](https://github.com/oceanprotocol/contracts/issues/491) - vesting. Talked to Alex C about fixing bug. We don't need the branch anymore, what was communicated in issue 491 is enough for them to take over there.
