### ISSUE TITLE
Replace conda with pip, to solve dependency problems

### ISSUE THREAD

**Issue by LinuxIsCool** [tokenspice/tokenspice#63]
**Motivation**

Conda was only introduced at the beginning of tokenspice so that a bunch of other numerical / data science packages didn't need specific installation. But it has led to problems:
- Can't have conda and brownie installed at once (at least as of spring 2020). But having brownie will help a lot for #52, and in general for rapid development at the solidity level.  
- Causes issues for some people just trying to run tokenspice (eg #62). 
- Conda's just heaver than pip. This is workable, but having just pip will reduce friction

**TODOs**
The main idea: replace conda with pip. 

This includes the following:
- [x] update README, replacing conda with pip. Perhaps also move to pipenv, see comment below
- [x] change related files: deprecate the environment.yml for conda, add a requirements.txt for conda. Ensure that requirements.txt includes all dependencies.
- [x] (as usual) all unit tests should pass 

Guidelines:
- Don't violate DRY
- Do _not_ have >1 installation paths (eg one for bash, one for fish). Just have one good default path that's as standard as possible
- Do _not_ make it specific to a given shell like bash or fish. It should work bash (the standard) and for fish (given that many early tokenspice folks use it)

**Comment by LinuxIsCool** [comment]
Related to #62

**Comment by trentmc** [comment]
I think we should simply deprecate the conda and use pip, given that conda is heavier than pip and less widely used. (And having >1 installation options will be a nightmare. Focus on the "fattest track" and make it great)

Accordingly, I recommend changing the title of this issue to "Replace conda with pip"

**Comment by nick-verida** [comment]
[requirements.txt](https://github.com/tokenspice/tokenspice/files/7158124/requirements.txt)

As a first step towards this, I've attached my requirements.txt 

Instructions are something like:

```
Create a virtual environment
pip3 install -r requirements.txt 
```

**Comment by trentmc** [comment]
> As a first step towards this, I've attached my requirements.txt

Cool!

FYI I've updated the description to lay out exactly what's needed. That requirements.txt can be an input to the work. Feel free to do a PR that does all the stuff at once, it would be my pleasure to review and merge it.

**Comment by trentmc** [comment]
Set to high priority because it's causing people problems in installing, and holding back solidity work.

**Comment by trentmc** [comment]
From https://github.com/tokenspice/tokenspice/issues/58#issuecomment-921687907:

> If you use pip now, I'd suggest using pipenv right away. That way you can try to push people to not mix and match too much (i.e. mix with system python or whatever) because that will cause problems on pip too.

**Comment by nick-verida** [comment]
`pipenv` is great, but it is layered on top of pip (and virtualenv)

I usually find it best if projects just provide a `requirements txt` (which everything supports) and then developers can choose to use it in pipenv (or conda) depending on their preference. 

I'll try to do a PR for this, but it will be next week at the earliest.

**Comment by trentmc** [comment]
This was fixed with the merge above.
https://github.com/tokenspice/tokenspice/commit/91f4f6e254bf7f9e20e9bfec1d78e80ba657d2d6
