### ISSUE TITLE
Fix continuous integration

### ISSUE THREAD

**Issue by trentmc** [tokenspice/tokenspice#96]
**Motivation**

TokenSPICE's CI tests are partly broken. When I do a PR, many CI tests fail. Some tests are too heavy to try to fix. Others are potentially worth keeping. The aim here is to revise the flow to something practical going forward for this stage of maturity of TokenSPICE: some tests, but low enough friction for fast progress. 

The Appendices below hold more info about pytest.yml and Codacy static linting.

**TODOs**

- [x] mypy isn't installed locally. It should likely be in requirements.txt. 
- [x] Ensure mypy tests pass locally
- [x] README should reference mypy
- [x] Get remote pytest passing https://github.com/tokenspice/tokenspice/commit/b208dc8bac0c3f0f65614910b3cf2304b9d2ab98
- [x] Does main branch README.md report that tests are passing (vs failing)? If no, fix. 
- [x] Choose a style guide and document it. Include how to handle docstrings. https://github.com/tokenspice/tokenspice/commit/30c24fa49ceffc7b97eac030f95a3625703932cf
- [x] Incorporate `black` to auto-fix many formatting issues. https://github.com/tokenspice/tokenspice/commit/30c24fa49ceffc7b97eac030f95a3625703932cf
- [x] Codacy [dashboard](https://app.codacy.com/gh/tokenspice/tokenspice/dashboard?branch=main) says "We stopped receiving your coverage results. Check if your CI workflow is set up correctly". Fix it.
- [x] mypy run fails again. fix it https://github.com/tokenspice/tokenspice/commit/a8f490273db7aa815232c60f231c5b103a80c632
- [x] Fix codacy static code analysis, by switching to pure pylint. Ensure both local & remote use same .pylintrc. https://github.com/tokenspice/tokenspice/commit/917a7498574f30dd76920844dc22aa3048a2d81a
- [x] Make changes until no pylint issues reported https://github.com/tokenspice/tokenspice/commit/6d2ce948c6bf72ac50fa71667ff15295b22af41d

**Appendix 1: pytest.yml contents**

`/.github/workflows/pytest.yml` was introduced as part of the codacy work. Inspecting it reveals there's a bunch of obsolete stuff
- e.g. running ganache and cloning Ocean contracts repo
- it's obsolete due to recent changes around using brownie: https://github.com/tokenspice/tokenspice/commit/330aad89ea2a90ecc3f16fbff03b3619c392ef8f, https://github.com/tokenspice/tokenspice/commit/780e8ccbcf5fe03fc882df1f8c447a759fa49bae

**Appendix 2: Codacy**

TokenSPICE currently uses Codacy for (i) code coverage (ii) style checks. We are keeping (i). This issue is concerned with (ii).

Datapoint: Ocean introduced Codacy static checks (ii) into its CI in early 2021, then in mid 2021 replaced it with codeclimate. Why: had trouble running tests if the email from our github was different from the one used for pushing the commit. Which meant Ocean had to reconfigure everything and didn’t have flexibility to change from personal to business accounts. 

Datapoint: @JohannSuarez introduced Codacy to TokenSPICE in Sep 26, 2021 in commit https://github.com/tokenspice/tokenspice/commit/22b784decd3d3629798aeda9d9757f28fdf476c1 for issue  #25. 

Datapoint: as of Oct 2021 @trangnv is unable to run `codacy-cli` locally on his macbook.

Datapoint: Codacy reports hundreds of errors. Many make sense to fix, and many are overkill.

Datapoint: run run codacy-cli locally with the same setup as remote, you need to a "Project API Token", which can only be granted to you by someone with appropriate Codacy permissions. Currently that's just Trent. This is a pain.

Datapoint: codacy-cli is a bit painful to use. Installing it is weird. It's poorly documented. It runs slowly, at least 30 s for a small scope, and several minutes for whole repo. It heavily churns the CPU as it runs.

Datapoint: Codacy static checks works by running several sub-tools including pylint.

Datapoint: pylint on its own gives a great approximation of all Codacy static checks. It's more lightweight.

Datapoint: Codacy tokenspice dashboard: https://app.codacy.com/gh/tokenspice/tokenspice/dashboard?branch=main

Datapoint: Codacy help on configuring code patterns: https://docs.codacy.com/repositories-configure/configuring-code-patterns/

**Comment by trentmc** [comment]
Another datapoint. As part of PR #95, for Ocean V3 market dynamics towards #28, I ran codacy locally. There were so many messages that it filled up my whole bash buffer (!).
